### ISSUE TITLE
Getting panic: `sql: Register called twice for driver postgres`

### ISSUE THREAD

**Issue by apaganobeleno** [wawandco/transporter#17]
Need to ensure transporter only registers postgres driver once.

**Comment by apaganobeleno** [comment]
Fixed, Adding historical description of the issue:
When using `godep`migrations had the transporter import at the top changed to use the godep version of the transporter library, resulting in a repeated init call of the pq and mysql libraries.

**Comment by fiatjaf** [comment]
If you arrived here from a generic Google search, see [this comment](https://github.com/lib/pq/issues/238#issuecomment-250018321).
